name: covid
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  url_launcher: ^5.4.10
  esys_flutter_share: ^1.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/back.jpg
    - asset/images/drawer.jpeg
    - asset/images/splash.jpeg
    - asset/images/logo2.png
    - asset/images/precaution.png
    - asset/images/cough.png
    - asset/images/play.jpg
    - asset/images/facebook.png
    - asset/images/instagram.png
    - asset/images/twitter.png
    - asset/images/github.png
    - asset/images/precautions/cough-01.jpeg
    - asset/images/precautions/cover-01.jpeg
    - asset/images/precautions/disinfect-01.jpeg
    - asset/images/precautions/distancing-01.jpeg
    - asset/images/precautions/mask-01.jpeg
    - asset/images/precautions/stay-02.jpeg
    - asset/images/precautions/washhand-01.jpeg
    - asset/images/symptoms/breath.jpeg
    - asset/images/symptoms/cough.jpeg
    - asset/images/symptoms/fatigue.jpeg
    - asset/images/symptoms/fever.jpeg
    - asset/images/symptoms/sore.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FiraSans
      fonts:
        - asset: asset/fonts/FiraSans-Thin.ttf
          weight: 100
        - asset: asset/fonts/FiraSans-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/FiraSans-Light.ttf
          weight: 300
        - asset: asset/fonts/FiraSans-Regular.ttf
          weight: 400
        - asset: asset/fonts/FiraSans-Medium.ttf
          weight: 500
        - asset: asset/fonts/FiraSans-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/FiraSans-Bold.ttf
          weight: 700
        - asset: asset/fonts/FiraSans-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/FiraSans-Black.ttf
          weight: 900

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
